In [4]:
import os
from glob import glob
from pathlib import Path
import sys
import os

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import sklearn as sk
import pickle
import copy
from treeinterpreter import treeinterpreter as ti
from sklearn.model_selection import LeaveOneGroupOut

In [5]:
notebooks = os.path.abspath('')
src = os.path.dirname(notebooks)
if not src in sys.path: 
    sys.path.append(src)

In [6]:
output_path = '../../files/out/video/'
# Global configuration path
glob_conf_path = '../global_config.py'

In [7]:
exec(open(glob_conf_path).read())

In [9]:
from sklearn.utils import shuffle

train_intensity_df = pd.read_csv(output_path + 'video_data_intensity_train.csv')
train_shuffled_df = shuffle(train_intensity_df, random_state=seed)
train_shuffled_df

filename  AU01_r_mean  AU01_r_stddevNorm  AU01_r_percentile20.0  \
265  A200_reg_p_3     0.463187           0.749064                    0.0   
74   A102_awe_p_3     0.175606           0.933978                    0.0   
148   A18_awe_v_1     0.188274           0.492815                    0.0   
3    A101_awe_p_4     0.061996           0.400991                    0.0   
233  A200_dou_p_2     0.182025           0.409290                    0.0   
..            ...          ...                ...                    ...   
24   A101_env_p_1     0.030968           0.449200                    0.0   
240  A200_env_p_2     0.102112           0.580680                    0.0   
31   A101_env_v_4     0.168026           0.816701                    0.0   
184   A18_gui_p_1     0.146868           0.699797                    0.0   
19   A101_dou_p_4     0.565163           0.335329                    0.0   

     AU01_r_percentile50.0  AU01_r_percentile80.0  AU01_r_iqr60_80-20  \
265               0.000000               0.203252            0.203252   
74                0.333333               0.056911            0.056911   
148               0.000000               0.198374            0.198374   
3                 0.000000               0.060976            0.060976   
233               0.000000               0.178049            0.178049   
..                     ...                    ...                 ...   
24                0.166667               0.029268            0.029268   
240               0.333333               0.069106            0.069106   
31                0.166667               0.046341            0.046341   
184               0.333333               0.089431            0.089431   
19                0.000000               0.605691            0.605691   

     AU01_r_numPeaks  AU02_r_mean  AU02_r_stddevNorm  ...  AU45_r_mean  \
265         0.188679     0.702141           0.733587  ...     0.224003   
74          0.056604     0.382604           0.703252  ...     0.310979   
148         0.075472     0.190862           0.426560  ...     0.207909   
3           0.358491     0.065202           0.477737  ...     0.046476   
233         0.245283     0.200819           0.541570  ...     0.226453   
..               ...          ...                ...  ...          ...   
24          0.132075     0.096300           0.376929  ...     0.308084   
240         0.150943     0.038659           0.353450  ...     0.295423   
31          0.094340     0.233069           0.599587  ...     0.283891   
184         0.037736     0.118299           0.550872  ...     0.239968   
19          0.358491     0.081605           0.558012  ...     0.308596   

     AU45_r_stddevNorm  AU45_r_percentile20.0  AU45_r_percentile50.0  \
265           0.199766                    0.0               0.000000   
74            0.467789                    0.0               0.166667   
148           0.572976                    0.0               0.333333   
3             0.181229                    0.0               0.000000   
233           0.214635                    0.0               0.000000   
..                 ...                    ...                    ...   
24            0.515232                    0.0               0.166667   
240           0.313167                    0.0               0.000000   
31            0.740826                    0.0               0.166667   
184           0.380419                    0.0               0.333333   
19            0.428860                    0.0               0.333333   

     AU45_r_percentile80.0  AU45_r_iqr60_80-20  AU45_r_numPeaks  video_id  \
265               0.171355            0.171355            0.650      A200   
74                0.084399            0.084399            0.100      A102   
148               0.020460            0.020460            0.025       A18   
3                 0.031714            0.031714            0.550      A101   
233               0.173913            0.173913            0.175      A200   
.. 

In [32]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y.unique())

LabelEncoder()

In [35]:
le.classes_

array([ 0,  3,  4,  6, 10, 18, 37, 40, 43])

In [34]:
le.transform(le.classes_)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
le.transform([4])

array([2])

In [16]:
train_idx, val_idx = logo.split(X, y, groups)

In [18]:
val_idx

(array([  0,   3,   4,   5,   9,  10,  14,  15,  22,  23,  25,  26,  27,
         30,  31,  35,  40,  41,  42,  43,  47,  48,  49,  50,  51,  55,
         56,  59,  61,  62,  64,  67,  68,  73,  75,  77,  78,  79,  84,
         85,  86,  87,  89,  91,  92,  93,  94,  96,  97, 103, 104, 105,
        107, 109, 113, 114, 117, 118, 119, 120, 121, 122, 123, 125, 126,
        127, 130, 132, 134, 138, 140, 142, 143, 145, 146, 148, 151, 153,
        154, 155, 156, 157, 158, 161, 162, 167, 170, 172, 178, 180, 185,
        193, 194, 197, 198, 203, 204, 205, 206, 207, 210, 212, 216, 217,
        218, 219, 220, 221, 222, 223, 224, 225, 229, 231, 232, 234, 236,
        237, 238, 240, 242, 245, 248, 249, 251, 253, 254, 256, 260, 261,
        262, 266, 267, 268, 270, 272, 275, 279, 281, 282, 283, 284, 286]),
 array([  1,   2,   6,   7,   8,  11,  12,  13,  16,  17,  18,  19,  20,
         21,  24,  28,  29,  32,  33,  34,  36,  37,  38,  39,  44,  45,
         46,  52,  53,  54,  57,  58,  60,  63,  

In [26]:
y_train.unique()

array([18,  0, 10,  6,  4, 43, 40,  3, 37])

In [43]:
from sklearn.ensemble import RandomForestClassifier

# Obtain X, y, and groups from the training dataset
X = train_shuffled_df.drop(columns=["filename", "video_id", "emotion_1_id", "group"])
y = train_shuffled_df.emotion_1_id
groups = train_shuffled_df.group
n_groups = len(groups.unique())

# Load best parameters and initialize classifier
file_path = os.path.join(output_path,'best_params','best_params_rf_intensity_video.sav')
best_params = pickle.load(open(file_path, 'rb'))
clf = RandomForestClassifier(**best_params)

# Perform LOGO CV (5 GROUPS)
data_tmp = [] # Initialize to store data
logo = LeaveOneGroupOut()

# iterate groups
for train_idx, val_idx in logo.split(X, y, groups):
    X_train, X_val, y_train, y_val = X.iloc[train_idx], X.iloc[val_idx], y.iloc[train_idx], y.iloc[val_idx]
    
    # Fit models
    clf.fit(X_train, y_train)
        
    # Step 0. Get prediction probabilities, bias, contributions, predicted class and store it in a DataFrame
    # dataframe will have shape (number of observations, number of targets) 
    prediction_proba, bias, contributions = ti.predict(clf, X_val)
    prediction = clf.predict(X_val)
    # iterate predictions on validation set one by one
    for i in range(len(X_val)):
        
        # pred_class_tmp = prediction[i]  
        
        # transform target label to index
        pred_class_tmp = le.transform([prediction[i]])[0]        
        
        bias_tmp = bias[i, pred_class_tmp]
        contributions_tmp = contributions[i, :, pred_class_tmp]
        data_tmp.append([bias_tmp] + contributions_tmp.tolist() + [pred_class_tmp])
                
interpretation_step_0_df = pd.DataFrame(data=data_tmp, columns=['bias']+X.columns.tolist()+['prediction'])
interpretation_step_0_df

AttributeError: 'list' object has no attribute 'head'

In [ ]:
# Step 1. Group by predicted class and calculate mean
interpretation_step_1_df = interpretation_step_0_df.groupby('prediction').mean().reset_index()
interpretation_step_1_df['emotion_1'] = interpretation_step_1_df['prediction'].map(emotion_num_to_emotion_eng_id)
interpretation_step_1_df = interpretation_step_1_df.drop(columns='prediction')

#interpretation_step_1_df

# Plot results
sns.set_style({'ytick.left': True})
mat = interpretation_step_1_df.drop(columns='bias').set_index(keys='emotion_id').transpose()
mat = mat.reindex(sorted(mat.columns), axis=1)
mat = mat.rename(var_name_to_feat, axis=0)
mat = mat.reindex(list(var_name_to_feat.values())).dropna()
mat.to_csv(os.path.join(output_path,'others','tmp','video_classifier_feature_contributions.csv'), index=True, header=True)

plt.figure(figsize=(30,40))
ax = sns.heatmap(mat, annot=True, annot_kws={"size": 12}, fmt='.4f', cmap=conf_cmap)
plt.yticks(va='center')
plt.xlabel('Emotion ID')
plt.ylabel('Feature')
plt.savefig(os.path.join(output_path,'others','report_video_classifier_feature_contributions.svg'), bbox_inches = 'tight')
plt.title('Late Fusion: Video Classifier Average Feature Contributions per Emotion')
plt.savefig(os.path.join(output_path,'others','video_classifier_feature_contributions.svg'), bbox_inches = 'tight')
plt.show()
sns.set_style({'ytick.left': False})